name: Dummy API

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'go-course/**'
      - 'go-course/*'
      - '.gitignore'
      - '*.(json|png|jpg|md)'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'go-course/**'
      - 'go-course/*'
      - '*.md'
      - '.gitignore'
      - '*.(json|png|jpg|md)'

env:
  CARGO_TERM_COLOR: always
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  IMAGE: dummy-api
  MAX_INSTANCES: 1
  MEMORY: 128Mi
  PORT: 3030
  REGION: asia-southeast1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: cargo test

    - name: Authenticate
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          . && \
        docker tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" "gcr.io/$PROJECT_ID/$IMAGE:latest"

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" && \
        docker push "gcr.io/$PROJECT_ID/$IMAGE:latest"

    # Deploy the Docker image to Google Cloud Run
    - name: Deploy
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'dummy-api'
        image: 'gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:latest'
        flags: '--project=${{ env.PROJECT_ID }} --platform=managed --port=${{ env.PORT }} --region=${{ env.REGION }} --allow-unauthenticated --max-instances=${{ env.MAX_INSTANCES }} --memory=${{ env.MEMORY }} --command=./dummy-api'
