name: Dummy API

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'basic-automated-tests/**'
      - 'project/**'
      - '*.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'basic-automated-tests/**'
      - 'project/**'
      - '*.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dummy-api

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose --release
